-- Generated by nwg-displays on 2026-09-17 at 22:06:20. Do not edit manually.

hl.monitor({
    output = "DP-4",
    mode = "1366x768@59.79",
    position = "0x312",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1366x0",
    scale = 1.0,
    vrr = 0
})
